### ISSUE TITLE
Suggestion using zappadock with credentials file

### ISSUE THREAD

**Issue by esentino** [dickermoshe/zappadock#1]
Hello, I had a problem with starting zappadock for a fresh project.
Before I started using zappa to deploy the simple application and I had configured `.aws/credentials` and `.aws/config` for development before. 
In config have set default region for usage with aws.
I lost half-hour to check what is wrong and why.
Zappadock searching for aws region only in `.aws/credentials` ignoring  `.aws/config`. Error message misleading that configuration for aws is wrong and pointing documentation where no information about setting region needed.

I suggest one of:
- adding information in `readme.MD` that region variable `region` in `.aws/credentials` profile is mandatory,
- adding some kind of message information that one of the needed variables in credentials profile is needed,
- adding handling `.aws/config` inheritance `default` profile for profiles in `.aws/credentials`.

**Comment by dickermoshe** [comment]
Fixed in Release 0.1.6
Zappadock will load entire `~/.aws` folder now.
