### ISSUE TITLE
Exposing port on runserver?

### ISSUE THREAD

**Issue by werkitmk** [dickermoshe/zappadock#3]
Hi, I am trying to run locally but when I visit localhost:8000 is not displaying anything. Is there an easy workaround?

**Comment by dickermoshe** [comment]
Add 
`EXPOSE 8000`
to the zappadock file

**Comment by dickermoshe** [comment]
I just updated the Package.
Run `pip install -U zappadock` to update
You will need to run `python manage.py runserver 0.0.0.0:8000`
See >>> https://stackoverflow.com/a/46326015
