### ISSUE TITLE
create docker container having archecticture i386 instead of arm64

### ISSUE THREAD

**Issue by tusharmesh** [dickermoshe/zappadock#5]
Want to know is it possible to use i386 arch inside the container instead arm64 on my m1. 
the dependencies are being installed for aarch64. but the lambda is deploying for x86_64.
how can i resolve this ?

**Comment by dickermoshe** [comment]
This package is just a simple wrapper of some basic Docker commands. 
For actual usage of Zappa, I suggest you raise an issue there.
